# Generated by Django 5.0.3 on 2024-03-14 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=100, verbose_name='name TM')),
                ('name_ru', models.CharField(max_length=100, verbose_name='name RU')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand-logo/', verbose_name='LOGO')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='Web Site')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brand',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='supersubcategory',
            options={'verbose_name': 'Supersubcategory', 'verbose_name_plural': 'Supersubcategories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='name RU'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_tm',
            field=models.CharField(max_length=100, verbose_name='name TM'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='name RU'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_tm',
            field=models.CharField(max_length=100, verbose_name='name TM'),
        ),
        migrations.AlterField(
            model_name='supersubcategory',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='name RU'),
        ),
        migrations.AlterField(
            model_name='supersubcategory',
            name='name_tm',
            field=models.CharField(max_length=100, verbose_name='name TM'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=100, verbose_name='name TM')),
                ('name_ru', models.CharField(max_length=100, verbose_name='name RU')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sku', models.CharField(choices=[('kg', 'kg'), ('pcs', 'pcs')], default='kg', help_text='Stock keeping unit', max_length=3, verbose_name='SKU')),
                ('upc', models.CharField(help_text='Universal Product Code', max_length=50, verbose_name='UPC')),
                ('stock_quantity', models.FloatField(blank=True, null=True)),
                ('description_tm', models.TextField(blank=True, null=True, verbose_name='description TM')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description RU')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_original', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
                ('supersubcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.supersubcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
    ]
