# Generated by Django 5.0.3 on 2024-03-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_favourite_product_alter_favourite_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
